package com.xxh.start1.mapper;

import com.xxh.start1.model.Notified;
import com.xxh.start1.model.NotifiedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NotifiedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFIED
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    long countByExample(NotifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFIED
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    int deleteByExample(NotifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFIED
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFIED
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    int insert(Notified record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFIED
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    int insertSelective(Notified record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFIED
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    List<Notified> selectByExampleWithRowbounds(NotifiedExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFIED
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    List<Notified> selectByExample(NotifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFIED
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    Notified selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFIED
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") Notified record, @Param("example") NotifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFIED
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    int updateByExample(@Param("record") Notified record, @Param("example") NotifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFIED
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    int updateByPrimaryKeySelective(Notified record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFIED
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    int updateByPrimaryKey(Notified record);
}