package com.xxh.start1.model;

public class Notified {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFIED.ID
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFIED.NOTIFIER
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    private Integer notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFIED.RECEIVER
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    private Integer receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFIED.OUTERID
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    private Long outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFIED.TYPE
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFIED.GMT_CREATE
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFIED.STATUS
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFIED.NOTIFIER_NAME
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    private String notifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFIED.OUTER_TITLE
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    private String outerTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFIED.ID
     *
     * @return the value of NOTIFIED.ID
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFIED.ID
     *
     * @param id the value for NOTIFIED.ID
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFIED.NOTIFIER
     *
     * @return the value of NOTIFIED.NOTIFIER
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public Integer getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFIED.NOTIFIER
     *
     * @param notifier the value for NOTIFIED.NOTIFIER
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public void setNotifier(Integer notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFIED.RECEIVER
     *
     * @return the value of NOTIFIED.RECEIVER
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public Integer getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFIED.RECEIVER
     *
     * @param receiver the value for NOTIFIED.RECEIVER
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFIED.OUTERID
     *
     * @return the value of NOTIFIED.OUTERID
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public Long getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFIED.OUTERID
     *
     * @param outerid the value for NOTIFIED.OUTERID
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public void setOuterid(Long outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFIED.TYPE
     *
     * @return the value of NOTIFIED.TYPE
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFIED.TYPE
     *
     * @param type the value for NOTIFIED.TYPE
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFIED.GMT_CREATE
     *
     * @return the value of NOTIFIED.GMT_CREATE
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFIED.GMT_CREATE
     *
     * @param gmtCreate the value for NOTIFIED.GMT_CREATE
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFIED.STATUS
     *
     * @return the value of NOTIFIED.STATUS
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFIED.STATUS
     *
     * @param status the value for NOTIFIED.STATUS
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFIED.NOTIFIER_NAME
     *
     * @return the value of NOTIFIED.NOTIFIER_NAME
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public String getNotifierName() {
        return notifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFIED.NOTIFIER_NAME
     *
     * @param notifierName the value for NOTIFIED.NOTIFIER_NAME
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public void setNotifierName(String notifierName) {
        this.notifierName = notifierName == null ? null : notifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFIED.OUTER_TITLE
     *
     * @return the value of NOTIFIED.OUTER_TITLE
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public String getOuterTitle() {
        return outerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFIED.OUTER_TITLE
     *
     * @param outerTitle the value for NOTIFIED.OUTER_TITLE
     *
     * @mbg.generated Wed Aug 14 15:57:07 CST 2019
     */
    public void setOuterTitle(String outerTitle) {
        this.outerTitle = outerTitle == null ? null : outerTitle.trim();
    }
}