create table NOTIFIED
(
	ID BIGINT default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_E29BE37A_40E4_4664_B549_7471955E248E) auto_increment
		constraint NOTIFIED_ID_UINDEX
			unique,
	NOTIFIER BIGINT,
	RECEIVER BIGINT,
	OUTERID BIGINT not null,
	TYPE INTEGER not null,
	GMT_CREATE BIGINT,
	STATUS INTEGER default 0 not null
);


